### ISSUE TITLE
How can I use synphot for an emission H-alpha nebula

### ISSUE THREAD

**Issue by dan-adi** [spacetelescope/synphot_refactor#360]
I am interested in computing the Object counts through my telescope and CCD camera and a H alpha filter. The object should be an emission nebula.
Do I need to use synphot to create a synthetic spectrum, or do I need to get the Flux data for my object from some Vizier catalog?
Don't know how to approach the problem.
The formula for computing counts is:
```
Targetelectrons = (Flux/PhotonEnergy) * QE * FilterBandwidth * EffectiveTelescopeAperture * imagescale^2
```
The unknown is the Flux in H-alpha.
A H-filter seems easy to construct:
```
Hydrogen_filter = SpectralElement(Box1D, amplitude=1, x_0=6563, width=30)
```

**Comment by dan-adi** [comment]
Could this be correct?

```
# Retrieve Object H-alpha Flux from VizieR in erg/s/cm²/Å else do a conversion for the whatever flux units you find
h_alpha_flux = your_h_alpha_flux * units.erg / (u.s * u.cm**2 * u.Angstrom)

# Define H-alpha Wavelength
h_alpha_wavelength = 656.3 * u.nm

# Create filter for H-alpha
Hydrogen_filter = SpectralElement(Box1D, amplitude=1, x_0=6563, width=30)

# Create Source Spectrum for H-alpha
spectrum = SourceSpectrum(ConstFlux1D, wave=h_alpha_wavelength, flux=h_alpha_flux)

# Convolve Source Spectrum with Hydrogen_filter
observed_spectrum = Observation(spectrum, Hydrogen_filter)

# Integrate Over Wavelength to Calculate Photon Count Rate
integrated_flux = observed_spectrum.integrate(flux_unit=units.FLAM)
```

**Comment by pllim** [comment]
Hello, @dan-adi , if you already have the data from your telescope and wants to *analyze* it, maybe you need https://specutils.readthedocs.io/en/stable/ and not this package.

If you want to *predict* what the data would have looked like with your telescope, you need actual throughput files for all the optical elements within your telescope. Usually a real filter is more complicated than Box1D model. You would also need a simulated spectrum of your observation object (before passing through any optical elements, usually the best you can do here is pick a theoretical model that can represent it). Then you need to renormalize the theoretical model to your telescope, say you know that such an object is going to be this magnitude through your filter, because theoretical model is not normalized to anything.

Maybe you would find https://learn.astropy.org/ useful? Though it might not cover your exact topic.

For general discussions, please go to https://community.openastronomy.org/c/astropy/8

Thank you for your interest.

**Comment by dan-adi** [comment]
> Hello, @dan-adi , if you already have the data from your telescope and wants to _analyze_ it, maybe you need https://specutils.readthedocs.io/en/stable/ and not this package.
> 
> If you want to _predict_ what the data would have looked like with your telescope, you need actual throughput files for all the optical elements within your telescope. Usually a real filter is more complicated than Box1D model. You would also need a simulated spectrum of your observation object (before passing through any optical elements, usually the best you can do here is pick a theoretical model that can represent it). Then you need to renormalize the theoretical model to your telescope, say you know that such an object is going to be this magnitude through your filter, because theoretical model is not normalized to anything.
> 
> Maybe you would find https://learn.astropy.org/ useful? Though it might not cover your exact topic.
> 
> For general discussions, please go to https://community.openastronomy.org/c/astropy/8
> 
> Thank you for your interest.

Thank you, I will also try the astropy comunity. I need to determine the flux so I can further use it to compute the exposure time needed through a H-alpha filter.
For point sources where we have a target V mag of 20 for example, it was easy to use synphot and a V filter to compute the expected flux density for such a source. 
For narrow band imaging it seems things are more complicated.
